learning_log/urls.py
from . import views
from django.urls import path


app_name = 'learning_log'
urlpatterns = [
    path('', views.home_page, name='Home'),
    path('main/', views.main_page, name='Main'),
    path('news/<int:newsid>/', views.news_page, name='News'),
]

learning_logs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_log.urls'))
]

learning_log/models.py
from django.db import models

class New_title(models.Model):
    mini_title = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.mini_title
        return self.title

class Entry(models.Model):
    new_title = models.ForeignKey(New_title, on_delete=models.CASCADE)
    text = models.TextField()
    date_add = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

learning_log/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import New_title

def home_page(request):
    return render(request, 'learning_log/home_page.html')

def main_page(request):
    return render(request, 'learning_log/main_page.html')

def news_page(request, newsid):
    if newsid == 0:
        return HttpResponse("<p><h1>Sorry page not fonud<h1></p>")
    elif newsid <= 100:
        return render(request, 'learning_log/news_page.html')
    else:
        return HttpResponse("<p><h1>Sorry page not fonud<h1></p>")

learning_log/templates/learning_log/base.html
<p>
    <a href="{% url 'learning_log:Home' %}">Home Page</a>
</p>
<p>
    <a href="{% url 'learning_log:Main' %}">Main Page</a>
</p>

{% block content %}{% endblock content %}

learning_log/templates/learning_log/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
    <h1>Hello in Home page!!!</h1>
</body>
</html>

learning_log/templates/learning_log/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
</head>
<body>
    <h1>Hello in Main page!!!</h1>
</body>
</html>

learning_log/templates/learning_log/news_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>News Page</title>
</head>
<body>
    <h1>Hello in News Page</h1>
</body>
</html>